name: Jenkins

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: eaudoh
          password: dckr_pat_m5fevXe6ldQCa2ouBPdGYZHOhLQ
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: eaudoh/jenkins
